import { registerVersoAnimation } from "../registry";
import { breathingRingsAnimation } from "./breathingRings";
import { inkTideAnimation } from "./inkTide";
import { lightTailorAnimation } from "./lightTailor";
import { sketchbookLivingAnimation } from "./sketchbookLiving";
import { porcelainMemoryAnimation } from "./porcelainMemory";
import { floatingWatercolorAnimation } from "./floatingWatercolor";
import { retableMiniatureAnimation } from "./retableMiniature";
import { prismObsidianAnimation } from "./prismObsidian";
import { celestialConstellationAnimation } from "./celestialConstellation";
import { paperOrigamiAnimation } from "./paperOrigami";
import { liquidGoldAnimation } from "./liquidGold";
import { vaporwaveSunAnimation } from "./vaporwaveSun";
import { starfieldHeartAnimation } from "./starfieldHeart";
import { origamiHeartAnimation } from "./origamiHeart";
import { trigonometricHeartAnimation } from "./trigonometricHeart";
import { geometricMorphingAnimation } from "./geometricMorphing";
import { floralBloomAnimation } from "./floralBloom";
import { inkTextAnimation } from "./inkText";
import { lightTextAnimation } from "./lightText";
import { breathTextAnimation } from "./breathText";
import { floatTextAnimation } from "./floatText";
import { revealTextAnimation } from "./revealText";
import { liquidTextAnimation } from "./liquidText";
import { morphTextAnimation } from "./morphText";

// Registration happens at module load, before any renderer resolves ids.
registerVersoAnimation(breathingRingsAnimation);
registerVersoAnimation(inkTideAnimation);
registerVersoAnimation(lightTailorAnimation);
registerVersoAnimation(sketchbookLivingAnimation);
registerVersoAnimation(porcelainMemoryAnimation);
registerVersoAnimation(floatingWatercolorAnimation);
registerVersoAnimation(retableMiniatureAnimation);
registerVersoAnimation(prismObsidianAnimation);
registerVersoAnimation(celestialConstellationAnimation);
registerVersoAnimation(paperOrigamiAnimation);
registerVersoAnimation(liquidGoldAnimation);
registerVersoAnimation(vaporwaveSunAnimation);
registerVersoAnimation(starfieldHeartAnimation);
registerVersoAnimation(origamiHeartAnimation);
registerVersoAnimation(trigonometricHeartAnimation);
registerVersoAnimation(geometricMorphingAnimation);
registerVersoAnimation(floralBloomAnimation);
registerVersoAnimation(inkTextAnimation);
registerVersoAnimation(lightTextAnimation);
registerVersoAnimation(breathTextAnimation);
registerVersoAnimation(floatTextAnimation);
registerVersoAnimation(revealTextAnimation);
registerVersoAnimation(liquidTextAnimation);
registerVersoAnimation(morphTextAnimation);
